fn main() {
    // The Worker bundle is generated by `npm run bundle-worker` (also run
    // automatically by `tauri dev` / `tauri build`). Fail early with a clear
    // message instead of a cryptic include_dir! error when it's missing.
    let dist = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("worker-dist");
    if !dist.join("manifest.json").exists() {
        panic!(
            "worker-dist/ is missing or incomplete. Run `npm run bundle-worker` in installer/ \
             first (it bundles the Worker source and dashboard assets this app deploys)."
        );
    }
    println!("cargo:rerun-if-changed=worker-dist");
    tauri_build::build()
}
